[package]
name = "blocking"
version = "0.4.7"
authors = ["Stjepan Glavina <stjepang@gmail.com>"]
edition = "2018"
description = "A thread pool for isolating blocking I/O in async programs"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/stjepang/blocking"
homepage = "https://github.com/stjepang/blocking"
documentation = "https://docs.rs/blocking"
keywords = ["async", "file", "stdio", "stdin", "process"]
categories = ["asynchronous", "concurrency"]
readme = "README.md"

[dependencies]
async-channel = "1.1.1"
atomic-waker = "1.0.0"
futures-lite = "0.1.7"
once_cell = "1.3.1"
waker-fn = "1.0.0"
